---

- hosts: all
  become: yes
  become_method: sudo
  tasks:
  - name: Install Apache2 Packages 
    apt:  name=apache2 state=present

  - name: Start Apache Service
    service: name=apache2 state=started enabled=true

  - name: Create Dir to Downlaod Tomcat. 
    file: path=/opt/SP/apps/tomcat state=directory

  - name: Install Java 1.8 
    apt: name=default-jdk state=present

  - name: Download Tomcat
    get_url: url=http://apachemirror.wuchna.com/tomcat/tomcat-9/v9.0.30/bin/apache-tomcat-9.0.30.tar.gz dest=/opt/SP/apps/tomcat.tar.gz mode=0755 

  - name: Extract Tomcat
    command: "tar zxf /opt/SP/apps/tomcat.tar.gz  -C /opt/SP/apps/tomcat --strip-components 1"

  - name: Copy user_project Project War Files
    copy: src=templates/userproject-0.0.1-SNAPSHOT.war dest=/opt/SP/apps/tomcat/webapps/ROOT.war mode=0644
    notify:
    - Restart Tomcat

  handlers:
  - name: Restart Tomcat
    shell: "nohup sh /opt/SP/apps/tomcat/bin/catalina.sh start" 
