node {
 
  registry = "devops311/userproject"
    registryCredential = 'dockerhubid'
	
 
 stage('Git-Checkout') {
   git 'https://github.com/devops311/user-project-application.git'
  }
    
 def project_path="application-code/code/userproject"
 
 dir(project_path) {
    stage('Maven-Clean') {
   sh label: '', script: 'mvn clean'
  }
    
 stage('Maven-Compile') {
   sh label: '', script: 'mvn compile'
  }
  
   stage('Maven-Package') {
   sh label: '', script: 'mvn package'
  }
	  stage('Maven-Install') {
   sh label: '', script: 'mvn install'
  }
 }
    def project_pathh="application-code"
	 
   dir(project_pathh) {
  stage('Docker-Stage-Deployment') {
   
	  
   docker build -t user_project-img .
    docker run -d -p 8081:80  --name user_project_container user_project-img 
  }  
  }
  
  stage('Docker image push to dockerhub'){
    docker.withRegistry( '', registryCredential ) {
         sh 'docker tag  user_project-img devops311/userproject'
        sh 'docker push devops311/userproject'
         
   }
  }
   }
}

