node {
 
  registry = "devops311/userproject"
    registryCredential = 'dockerhubid'
	
 
 stage('Git-Checkout') {
   git 'https://github.com/devops311/user-project-application.git'
  }
    
 def project_path="application-code/code/userproject"
 
 dir(project_path) {
   stage('Maven-Clean') {
   sh label: '', script: 'mvn clean'
  }
    
 stage('Maven-Compile') {
   sh label: '', script: 'mvn compile'
  }
  
   stage('Maven-Package') {
   sh label: '', script: 'mvn package'
  }
 }
    def project_path="application-code"
	 
   dir(project_path) {
  stage('Docker-Stage-Deployment') {
   sh label: '', script: 'docker-compose up -d --build'
  }
  

  
  stage('Docker image push to dockerhub'){
   
   
     docker.withRegistry( '', registryCredential ) {
         sh 'docker tag quality-assurence_userproject devops311/userproject'
        sh 'docker push devops311/userproject'
         
   }
  }
  

	}

